In [1]:
import numpy as np
arr = np.arange(24)


In [3]:
print("Original 1D array:")
print(arr)
print("Shape:", arr.shape)
print("-" * 40)

Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Shape: (24,)
----------------------------------------


In [4]:
reshaped = arr.reshape(4, 3, 2)
print("After Reshape (4, 3, 2):")
print(reshaped)
print("Shape:",reshaped.shape)
print("-" * 40)

After Reshape (4, 3, 2):
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
Shape: (4, 3, 2)
----------------------------------------


In [6]:
transposed = reshaped.transpose(0, 2, 1)
print("After Transpose (4, 2, 3):")
print(transposed)
print("Final Shape:", transposed.shape)

After Transpose (4, 2, 3):
[[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
Final Shape: (4, 2, 3)
