In [16]:
import numpy as np
np.random.seed(42)
scores = np.random.randint(50, 101, size=(5,3))
mean_scores = np.mean(scores, axis=0)
centered_scores = scores - mean_scores

In [17]:
print("original scores:")
print (scores)
print("\nMean of Each Subject:")
print(mean_scores)
print("\nCentered (Normalized) Scores:")
print(centered_scores)

original scores:
[[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 73]]

Mean of Each Subject:
[82.6 70.4 70.4]

Centered (Normalized) Scores:
[[  5.4   7.6  -6.4]
 [  9.4 -13.4  -0.4]
 [  5.4  -2.4   1.6]
 [-22.6 -10.4   2.6]
 [  2.4  18.6   2.6]]
